# Generated by Django 4.2.5 on 2023-10-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
